
version: '3.8'
services:

  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - 5000:5000
    volumes:
      - .:/app/api-server
    networks:
      - weblyft
    env_file:
      - ./api-server/.env

  docker-mgr:
    build: ./docker-mgr
    container_name: docker-mgr
    ports:
      - 9000:9000
    volumes:
      - .:/app/docker-mgr
    networks:
      - weblyft
    env_file:
      - ./docker-mgr/.env

  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - 8080:8080
    volumes:
      - .:/app/reverse-proxy
    networks:
      - weblyft
    env_file:
      - ./reverse-proxy/.env

networks:
  weblyft:
    driver: bridge

volumes:
  public: